version: '3.1'
services:
    nginx:
        build: docker/nginx
        command: nginx -g "daemon off;"
        volumes:
            - ./:/var/www
        links:
            - app
        ports:
            - "80:80"

    app:
        build: docker/php
        command: php-fpm
        volumes:
            - ./:/var/www
        working_dir: /var/www
        ports:
            - "9000:9000"
        env_file: .env
        links:
            - db

    db:
        image: postgres:latest
        restart: always
        volumes:
            - /postgresdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"